name: Node.js CI
env:
  NODE_ENV: production
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Print environment variable
        run: echo $NODE_ENV
      - name: Use Repo Secret
        run: echo "Repo Secret:${{secrets.API_KEY}}"
      - name: Use Environment Secret
        run: echo "Environment Secret:${{secrets.PROD_DB_PASSWORD}}"
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: npm run build --if-present
      - name: Run Tests
        run: npm test
